import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "MATVEY-NE-LOX",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png",
    shortcut: "/icon.png",
    apple: "/icon.png",
  }
};

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`} >
      <body className="min-h-full flex flex-col">
        {children}
      </body>
    </html>
  );
}
